### ISSUE TITLE
example 1_Accumulator.sol getSum function

### ISSUE THREAD

**Issue by Pafaul** [tonlabs/samples#78]
When the contract 1_Accumulator.sol is deployed to the test network, the "add" method works correctly, but at the same time, when the "getSum" method is called, nothing happens, only a Message expired error occurs (code 1006). However, adding call to tvm.accept solves the problem and the GetSum function works correctly.

**Comment by SilkovAlexander** [comment]
Hello, thank you for a report. This function is a getter function and it should be called locally for not to spend gas on it. https://docs.ton.dev/86757ecb2/p/8080e6-tonos-cli/t/321a91
